q-hopper-backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "review",to: "pages#review"

  # Defines the root path route ("/")
  # root "posts#index"
  get '/map', to: 'restaurants#restaurant_map', as: :restaurant_map
  get '/test', to: 'restaurants#test'


  resources :restaurants do

    resources :reviews, only:[:index, :new, :create, :show]
    post '/join_queue',  to: 'bookings#join_queue'
    patch '/accept_booking', to: 'bookings#accept_booking'
    resources :bookings, only: [:new, :create, :edit, :update,]

    collection do
      get '/italian', to: 'restaurants#italian'
      get '/mexican', to: 'restaurants#mexican'
      get '/indian', to: 'restaurants#indian'
      get '/chinese', to: 'restaurants#chinese'
      get '/thai', to: 'restaurants#thai'
      get '/american', to: 'restaurants#american'
    end
  end
  # Booking routes
  resources :bookings do
    patch :complete_booking, on: :collection

    get :completed, on: :collection
  end
  # Restaurant user view
  resources :venues do
    post '/add_group', to: 'venues#add_group'
  end
end

q-hopper-backend/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates :user, presence: true
end

q-hopper-backend/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :new, :create, :destroy]
  def index
    @bookings = Booking.where(user_id: current_user.id, accepted: false)
    @joined = @bookings.find_by(join: true)
    #For each of the bookings return the results before the created date timestamp
    @booking_infos = []
    @bookings.each do |booking|
      @booking_infos << {
        booking: booking,
        queue_position: Booking.where("restaurant_id=? AND created_at >= ? AND accepted = false",booking.restaurant_id, booking.created_at).count
      }
    end
  end

  def show

  end

  def new

  end

  def create
    booking= Booking.new(booking_params)
    #booking= Booking.new(user:current_user,restaurant_id:params[:id])
    if booking.save
      redirect_to bookings_path
    else
      redirect_to restaurant_path(params[:id])
    end
  end

  def join_queue
    @restaurant= Restaurant.find(params[:restaurant_id])
    booking= Booking.new(user:current_user,restaurant: @restaurant, accepted: false, completed: false)
    if booking.save
      redirect_to bookings_path
    else
      redirect_to restaurant_path(params[:id])
    end
  end

  def accept_booking
    @booking = Booking.find(params[:restaurant_id])
    @booking.update(accepted: true)
    user = @booking.user

    Booking.where(user: @booking.user,accepted: false).destroy_all
    redirect_to completed_bookings_path
  end

  def complete_booking
    @booking = Booking.find(params[:booking_id])
    @booking.update(completed: true)
  end

  def destroy
    @booking.destroy()
    redirect_to bookings_path
  end

  def completed
    @bookings = Booking.where(user_id: current_user.id, accepted: true)
  end

  private
  def booking_params
    params.require(:booking).permit(:name)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end


end

q-hopper-backend/app/views/bookings/_booking_card.html.erb
<div class="card-booking" style="background-image: linear-gradient(rgba(18, 16, 16, 0.9), rgba(62, 53, 53, 0.5)), url('https://source.unsplash.com/random/?restaurant&<%= rand(1000) %>'); background-size: cover; background-position: center;">
    <div class="card-header">
        <h2><%= booking.restaurant.name%></h2>
        <div class="queue-position" style="text-align: center;">
            <div>
              <span class="number" style="text-align: bottom;"><%=queue_position%></span>
            </div>
            <div>
              <span class="text">Que Position</span>
            </div>
        </div>
    </div>
    <div class="card-body">
        <p class="rating"><strong>Rating:</strong> 10/10</p>
        <p class="est-time"><strong>Est Time:</strong> 15 min</p>
    </div>

    <%if status == 'joined'%>
      <div class="card-footer">
          <div class="footer-button-s">
              <a href="<%= booking_path(booking.id) %>" data-turbo-method="delete">Leave Queue</a>
          </div>
          <div class="footer-button">
              <a href="<%= restaurant_accept_booking_path(booking.id) %>"> Accept Booking</a>
          </div>
      </div>

    <%else%>
      <div class="card-footer">
          <div class="footer-button-s">
              <a href="<%= restaurant_path(booking.restaurant.id) %>">Details</a>
          </div>
          <div class="footer-button">
              <a href="<%= booking_path(booking.id) %>" data-turbo-method="delete">Leave Queue</a>
          </div>
      </div>
    <%end%>
</div>

q-hopper-backend/app/views/bookings/_booking_completed_card.erb
<div class="container" style="padding-top: 25px; padding-bottom: 100px;">
  <% @bookings.each do |booking|%>
<div class="card-booking" style="background-image: linear-gradient(rgba(18, 16, 16, 0.9), rgba(62, 53, 53, 0.5)), url('https://source.unsplash.com/random/?restaurant&<%= rand(1000) %>'); background-size: cover; background-position: center;">
    <div class="card-header">
        <h2><%= booking.restaurant.name%></h2>
    </div>
    <div class="card-footer">
        <div class="footer-button-s">
            <a href="<%= restaurant_path(booking.restaurant.id) %>">Details</a>
        </div>
            <div class="footer-button">
            <a href="<%= new_restaurant_review_path(booking.restaurant_id) %>">Leave Review</a>
        </div>
    </div>
</div>
  <%end%>
</div>

q-hopper-backend/app/views/bookings/_booking_joined_card.html.erb
<div class="card-booking" style="background-image: linear-gradient(rgba(18, 16, 16, 0.9), rgba(62, 53, 53, 0.5)), url('https://source.unsplash.com/random/?restaurant&<%= rand(1000) %>'); background-size: cover; background-position: center;"
data-controller = 'countdown'
data-countdown-text-value = "<%=booking.updated_at%>"
data-countdown-booking-value = "<%=booking.id%>"
data-countdown-card-type-value = ":warning">

    <div class="card-header">
        <h2><%= booking.restaurant.name%></h2>

    </div>
    <div class="card-body">
        <p class="rating" data-countdown-target = 'timer'></p>
    </div>


    <div class="card-footer">
        <div class="footer-button-s">
            <a href="<%= booking_path(booking.id) %>" data-turbo-method="delete">Leave Queue</a>
        </div>
        <div class="footer-button">
            <a href="<%= restaurant_accept_booking_path(booking.id) %>" data-turbo-method="patch"> Accept Booking</a>
        </div>
    </div>


</div>

q-hopper-backend/app/views/bookings/_booking_list.html.erb
<div class="container" style="padding-top: 25px; padding-bottom: 100px;">
  <% booking_infos.each do |booking_info|%>
    <%booking= booking_info[:booking]%>
    <%= render 'booking_card', booking: booking, queue_position: booking_info[:queue_position], status: 'not_joined'%>
  <%end%>
</div>

q-hopper-backend/app/views/bookings/completed.html.erb
<!-- This is the  Que / Completed toggle -->

<div class="container-fluid py-3 fixed-section">
  <div class="btn-group d-flex justify-content-center" role="group" aria-label="Vertical radio toggle button group">
    <a href="<%= bookings_path %>" class="btn btn-outline-secondary mx-2" style="height: 30px; width: 50%; align-content: center;">Queue</a>
    <a href="<%= completed_bookings_path %>" class="btn btn-outline-primary mx-2" style="height: 30px; width: 50%; align-content: center;">Completed</a>
  </div>
</div>

<%= render 'booking_completed_card', booking_infos: @bookings%>


<!-- Footer for the Queue (do not render as I have had to do a manual thing - cyrus) -->
<footer class="footer">
    <nav class="footer-nav">
        <div class="footer-section">
            <a href="<%= restaurant_map_path %>">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/ofarf6aoairysld5eghg.png" alt="Home">
                <span>Search</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="<%= bookings_path %>">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/xfjzjdi2tbeyb8wwzoja.png" alt="About">
                <span style="color: #E82E64">Queue</span>
            </a>
        </div>
               <div class="footer-section">
            <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="dropdown-item">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/hddpgefap6eu4ce1dmoe.png" alt="Contact">
                <span>Account</span>
            </a>
        </div>
    </nav>
</footer>

q-hopper-backend/app/views/bookings/index.html.erb
<!-- This is the  Que / Completed toggle -->

<div class="container-fluid py-3 fixed-section">
  <div class="btn-group d-flex justify-content-center" role="group" aria-label="Vertical radio toggle button group">
    <a href="<%= bookings_path %>" class="btn btn-outline-primary mx-2" style="height: 30px; width: 50%; align-content: center;">Queue</a>
    <a href="<%= completed_bookings_path %>" class="btn btn-outline-secondary mx-2" style="height: 30px; width: 50%; align-content: center;">Completed</a>
  </div>
</div>
<%if @joined%>
  <div style="padding-top: 25px; padding-bottom: 100px;">
   <%= render 'booking_joined_card', booking: @joined, queue_position: 0, status: 'joined'%>

  </div>
<%else%>
  <%= render 'booking_list', booking_infos: @booking_infos, status: 'not_joined'%>
<%end%>


<!-- Footer for the Queue (do not render as I have had to do a manual thing - cyrus) -->
<%= render 'shared/footer'%>