q-hopper-backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "review",to: "pages#review"

  # Defines the root path route ("/")
  # root "posts#index"
  get '/map', to: 'restaurants#restaurant_map', as: :restaurant_map
  get '/test', to: 'restaurants#test'


  resources :restaurants do

    resources :reviews, only:[:index, :new, :create, :show]
    post '/join_queue',  to: 'bookings#join_queue'
    patch '/accept_booking', to: 'bookings#accept_booking'
    resources :bookings, only: [:new, :create, :edit, :update,]

    collection do
      get '/italian', to: 'restaurants#italian'
      get '/mexican', to: 'restaurants#mexican'
      get '/indian', to: 'restaurants#indian'
      get '/chinese', to: 'restaurants#chinese'
      get '/thai', to: 'restaurants#thai'
      get '/american', to: 'restaurants#american'
    end
  end
  # Booking routes
  resources :bookings do
    patch :complete_booking, on: :collection

    get :completed, on: :collection
  end
  # Restaurant user view
  resources :venues do
    post '/add_group', to: 'venues#add_group'
  end
end

q-hopper-backend/app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cuisine, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :details, presence: true
end

q-hopper-backend/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :new, :create]
  skip_before_action :authenticate_user!, only: [:index, :show, :restaurant_map]

  def index
    @restaurants = Restaurant.all
      if params[:query].present?
        @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
      end

      respond_to do |format|
        format.html
        format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
      end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = @restaurant.reviews.order(created_at: :desc)
    @booking_status = Booking.where(restaurant_id: @restaurant.id, user: current_user).last
  end

  def new

  end

  def create

  end


  def test
    @restaurants = Restaurant.all
  end

  def restaurant_map
    @restaurants = Restaurant.all
    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        info_window_html: render_to_string(partial: "map_card", locals: {restaurant: restaurant}),
        marker_html: render_to_string(partial: "shared/marker")
      }
    end
  end

  def italian
    @restaurants = Restaurant.where(cuisine: "Italian")

    if params[:query].present?
      @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
    end
  end

  def mexican
    @restaurants = Restaurant.where(cuisine: "Mexican")

    if params[:query].present?
      @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
    end
  end

  def indian
    @restaurants = Restaurant.where(cuisine: "Indian")

    if params[:query].present?
      @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
    end
  end

  def chinese
    @restaurants = Restaurant.where(cuisine: "Chinese")

    if params[:query].present?
      @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
    end
  end

  def thai
    @restaurants = Restaurant.where(cuisine: "Thai")

    if params[:query].present?
      @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
    end
  end

  def american
    @restaurants = Restaurant.where(cuisine: "American")

    if params[:query].present?
      @restaurants = @restaurants.where("name ILIKE ?", "%#{params[:query]}%")
    end

    respond_to do |format|
      format.html
      format.text { render partial: 'restaurants/list-card', locals: { restaurants: @restaurants}, formats: [:html] }
    end
  end


  private

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

q-hopper-backend/app/views/restaurants/_list-card.erb
<div class="container" style="padding-top: 20px;">
  <div class="row justify-content-center" data-search-restaurants-target="list">
    <% @restaurants.each do |r| %>
      <div class="col-md-4">
        <div class="card mb-3" style="background-color: white;border-radius: 10px;box-shadow: rgba(149, 157, 165, 0.2) 0px 8px 24px;">
          <div style="padding: 15px;">
          <div class="card-img-top" style="background-image: url('https://source.unsplash.com/random/?restaurant&<%= rand(1000) %>'); height: 200px; background-size: cover; border-radius: 10px;"></div>
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= r.name %></h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <div class="row">
              <div class="button-container-index">
                <a href="<%= restaurant_path(r.id) %>" class="btn btn-info btn-block btn-small">Details</a>
                <%= link_to "Join Queue", restaurant_join_queue_path(r.id), class: "btn btn-primary btn-block btn-big", data: { turbo_method: :post } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

q-hopper-backend/app/views/restaurants/american.erb
<div class="container-fluid py-0 fixed-section" data-controller="search-restaurants">

  <!-- This is the search bar -->

  <div class="container-restaurant">
    <%= form_with url: restaurants_path, method: :get, html: {class: "mb-4", data: {search_restaurants_target: "form"}} do |f|%>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search for a restaurant",
                        value: params[:query],
                        data: {search_restaurants_target: "input",
                        action: "keyup->search-restaurants#update"}%>
      <%end%>
  </div>

<!-- This is the cards for the filters  -->

  <div class="row flex-nowrap overflow-auto m-2" style="width: 100vw;">
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="italian" data-type-target="input">
      <label for="italian"><i class="icon fa-solid fa-pizza-slice"></i><br>Italian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="mexican">
      <label for="mexican"><i class="icon fa-solid fa-pepper-hot"></i><br>Mexican</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="indian">
      <label for="indian"><i class="icon fa-solid fa-bowl-food"></i><br>Indian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="chinese">
      <label for="chinese"><i class="icon fa-solid fa-bowl-rice"></i><br>Chinese</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="thai">
      <label for="thai"><i class="icon fa-solid fa-shrimp"></i><br>Thai</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" checked type="checkbox" id="american">
      <label for="american"><i class="icon fa-solid fa-burger"></i><br>American</label>
    </div>
  </div>

  <div class="card-container">
    <%= render "list-card", restaurants:@restaurants%>
  </div>

</div>


<!-- Footer for the home page (do not render as I have had to do a manual thing - cyrus) -->
<footer class="footer">
    <nav class="footer-nav">
        <div class="footer-section">
            <a href="map">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/ofarf6aoairysld5eghg.png" alt="Home">
                <span>Search</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="bookings">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/xfjzjdi2tbeyb8wwzoja.png" alt="About">
                <span style="color: #E82E64">Queue</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="dropdown-item">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/hddpgefap6eu4ce1dmoe.png" alt="Contact">
                <span>Log out</span>
            </a>
        </div>
    </nav>
</footer>

<!-- toggle for the view component -->
<div class="fixed-button">
    <a href="<%= restaurant_map_path %>">
        <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715869457/rghwiicljemcv57a50ga.png" alt="Button Image">
    </a>
</div>

q-hopper-backend/app/views/restaurants/chinese.erb
<div class="container-fluid py-0 fixed-section" data-controller="search-restaurants">

  <!-- This is the search bar -->

  <div class="container-restaurant">
    <%= form_with url: restaurants_path, method: :get, html: {class: "mb-4", data: {search_restaurants_target: "form"}} do |f|%>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search for a restaurant",
                        value: params[:query],
                        data: {search_restaurants_target: "input",
                        action: "keyup->search-restaurants#update"}%>
      <%end%>
  </div>

<!-- This is the cards for the filters  -->

  <div class="row flex-nowrap overflow-auto m-2" style="width: 100vw;">
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="italian" data-type-target="input">
      <label for="italian"><i class="icon fa-solid fa-pizza-slice"></i><br>Italian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="mexican">
      <label for="mexican"><i class="icon fa-solid fa-pepper-hot"></i><br>Mexican</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="indian">
      <label for="indian"><i class="icon fa-solid fa-bowl-food"></i><br>Indian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" checked type="checkbox" id="chinese">
      <label for="chinese"><i class="icon fa-solid fa-bowl-rice"></i><br>Chinese</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="thai">
      <label for="thai"><i class="icon fa-solid fa-shrimp"></i><br>Thai</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="american">
      <label for="american"><i class="icon fa-solid fa-burger"></i><br>American</label>
    </div>
  </div>

  <div class="card-container">
    <%= render "list-card", restaurants:@restaurants%>
  </div>

</div>


<!-- Footer for the home page (do not render as I have had to do a manual thing - cyrus) -->
<footer class="footer">
    <nav class="footer-nav">
        <div class="footer-section">
            <a href="map">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/ofarf6aoairysld5eghg.png" alt="Home">
                <span>Search</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="bookings">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/xfjzjdi2tbeyb8wwzoja.png" alt="About">
                <span style="color: #E82E64">Queue</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="dropdown-item">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/hddpgefap6eu4ce1dmoe.png" alt="Contact">
                <span>Log out</span>
            </a>
        </div>
    </nav>
</footer>

<!-- toggle for the view component -->
<div class="fixed-button">
    <a href="<%= restaurant_map_path %>">
        <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715869457/rghwiicljemcv57a50ga.png" alt="Button Image">
    </a>
</div>

q-hopper-backend/app/views/restaurants/index.html.erb
<div class="container-fluid py-0 fixed-section" data-controller="search-restaurants">

  <!-- This is the search bar -->

  <div class="container-restaurant">
    <%= form_with url: restaurants_path, method: :get, html: {class: "mb-4", data: {search_restaurants_target: "form"}} do |f|%>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search for a restaurant",
                        value: params[:query],
                        data: {search_restaurants_target: "input",
                        action: "keyup->search-restaurants#update"}%>
      <%end%>
  </div>

<!-- This is the cards for the filters  -->

  <div class="row flex-nowrap overflow-auto m-2" style="width: 100vw;">
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="italian" data-type-target="input">
      <label for="italian"><i class="icon fa-solid fa-pizza-slice"></i><br>Italian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="mexican">
      <label for="mexican"><i class="icon fa-solid fa-pepper-hot"></i><br>Mexican</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="indian">
      <label for="indian"><i class="icon fa-solid fa-bowl-food"></i><br>Indian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="chinese">
      <label for="chinese"><i class="icon fa-solid fa-bowl-rice"></i><br>Chinese</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="thai">
      <label for="thai"><i class="icon fa-solid fa-shrimp"></i><br>Thai</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="american">
      <label for="american"><i class="icon fa-solid fa-burger"></i><br>American</label>
    </div>
  </div>

  <div class="card-container">
    <%= render "list-card", restaurants:@restaurants%>
  </div>

</div>


<!-- Footer for the home page (do not render as I have had to do a manual thing - cyrus) -->
<footer class="footer">
    <nav class="footer-nav">
        <div class="footer-section">
            <a href="map">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860283/qxksgyduenfel07lmr9l.png" alt="Home">
                <span style="color: #E82E64">Search</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="bookings">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/nmesasdrerguhyguwdxt.png" alt="About">
                <span>Queue</span>
            </a>
        </div>
             <div class="footer-section">
            <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="dropdown-item">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/hddpgefap6eu4ce1dmoe.png" alt="Contact">
                <span>Account</span>
            </a>
        </div>
    </nav>
</footer>


<!-- toggle for the view component -->
<div class="fixed-button">
    <a href="<%= restaurant_map_path %>">
        <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715869457/rghwiicljemcv57a50ga.png" alt="Button Image">
    </a>
</div>

q-hopper-backend/app/views/restaurants/indian.erb
<div class="container-fluid py-0 fixed-section" data-controller="search-restaurants">

  <!-- This is the search bar -->

  <div class="container-restaurant">
    <%= form_with url: restaurants_path, method: :get, html: {class: "mb-4", data: {search_restaurants_target: "form"}} do |f|%>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search for a restaurant",
                        value: params[:query],
                        data: {search_restaurants_target: "input",
                        action: "keyup->search-restaurants#update"}%>
      <%end%>
  </div>

<!-- This is the cards for the filters  -->

  <div class="row flex-nowrap overflow-auto m-2" style="width: 100vw;">
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="italian" data-type-target="input">
      <label for="italian"><i class="icon fa-solid fa-pizza-slice"></i><br>Italian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="mexican">
      <label for="mexican"><i class="icon fa-solid fa-pepper-hot"></i><br>Mexican</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" checked type="checkbox" id="indian">
      <label for="indian"><i class="icon fa-solid fa-bowl-food"></i><br>Indian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="chinese">
      <label for="chinese"><i class="icon fa-solid fa-bowl-rice"></i><br>Chinese</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="thai">
      <label for="thai"><i class="icon fa-solid fa-shrimp"></i><br>Thai</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="american">
      <label for="american"><i class="icon fa-solid fa-burger"></i><br>American</label>
    </div>
  </div>

  <div class="card-container">
    <%= render "list-card", restaurants:@restaurants%>
  </div>

</div>


<!-- Footer for the home page (do not render as I have had to do a manual thing - cyrus) -->
<footer class="footer">
    <nav class="footer-nav">
        <div class="footer-section">
            <a href="map">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/ofarf6aoairysld5eghg.png" alt="Home">
                <span>Search</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="bookings">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/xfjzjdi2tbeyb8wwzoja.png" alt="About">
                <span style="color: #E82E64">Queue</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="dropdown-item">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/hddpgefap6eu4ce1dmoe.png" alt="Contact">
                <span>Log out</span>
            </a>
        </div>
    </nav>
</footer>

<!-- toggle for the view component -->
<div class="fixed-button">
    <a href="<%= restaurant_map_path %>">
        <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715869457/rghwiicljemcv57a50ga.png" alt="Button Image">
    </a>
</div>

q-hopper-backend/app/views/restaurants/italian.erb
<div class="container-fluid py-0 fixed-section" data-controller="search-restaurants">

  <!-- This is the search bar -->

  <div class="container-restaurant">
    <%= form_with url: restaurants_path, method: :get, html: {class: "mb-4", data: {search_restaurants_target: "form"}} do |f|%>
      <%= f.text_field :query,
                        class: "form-control",
                        placeholder: "Search for a restaurant",
                        value: params[:query],
                        data: {search_restaurants_target: "input",
                        action: "keyup->search-restaurants#update"}%>
      <%end%>
  </div>

<!-- This is the cards for the filters  -->

  <div class="row flex-nowrap overflow-auto m-2" style="width: 100vw;">
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" checked type="checkbox" id="italian" data-type-target="input">
      <label for="italian"><i class="icon fa-solid fa-pizza-slice"></i><br>Italian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="mexican">
      <label for="mexican"><i class="icon fa-solid fa-pepper-hot"></i><br>Mexican</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="indian">
      <label for="indian"><i class="icon fa-solid fa-bowl-food"></i><br>Indian</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="chinese">
      <label for="chinese"><i class="icon fa-solid fa-bowl-rice"></i><br>Chinese</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="thai">
      <label for="thai"><i class="icon fa-solid fa-shrimp"></i><br>Thai</label>
    </div>
    <div class="col-auto mr-3 p-0" data-controller="type" data-action="change->type#select">
      <input class="type" type="checkbox" id="american">
      <label for="american"><i class="icon fa-solid fa-burger"></i><br>American</label>
    </div>
  </div>

  <div class="card-container">
    <%= render "list-card", restaurants:@restaurants%>
  </div>

</div>


<!-- Footer for the home page (do not render as I have had to do a manual thing - cyrus) -->
<footer class="footer">
    <nav class="footer-nav">
        <div class="footer-section">
            <a href="map">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/ofarf6aoairysld5eghg.png" alt="Home">
                <span>Search</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="bookings">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/xfjzjdi2tbeyb8wwzoja.png" alt="About">
                <span style="color: #E82E64">Queue</span>
            </a>
        </div>
        <div class="footer-section">
            <a href="<%= destroy_user_session_path %>" data-turbo-method="delete" class="dropdown-item">
                <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715860282/hddpgefap6eu4ce1dmoe.png" alt="Contact">
                <span>Log out</span>
            </a>
        </div>
    </nav>
</footer>

<!-- toggle for the view component -->
<div class="fixed-button">
    <a href="<%= restaurant_map_path %>">
        <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715869457/rghwiicljemcv57a50ga.png" alt="Button Image">
    </a>
</div>

q-hopper-backend/app/views/restaurants/show.html.erb
<div class="container-show">


  <!-- Centered name -->
  <div class="header-show">
  <h5 class="text-center"><%= @restaurant.name %></h5>
  </div>

  <%= render "carousel", restaurants:@restaurants%>

  <!-- Cards -->
  <div class="row mt-2">

    <div class="col-4 col-custom">
      <div class="card rounded-custom" style="height: 80px; background-color: white;border-radius: 10px;box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
        <div class="card-body text-center">
          <div>
          <h1><i class="fa-solid fa-pizza-slice"></i></h1>
          </div>
          <div>
          Italian
          </div>
        </div>
      </div>
    </div>


    <div class="col-4 col-custom">
      <div class="card rounded-custom" style="height: 80px; background-color: white;border-radius: 10px;box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
        <div class="card-body text-center">
          <h1>7.9</h1>
          <div>
          Rating
          </div>
        </div>
      </div>
    </div>


    <div class="col-4 col-custom">
      <div class="card rounded-custom" style="height: 80px; background-color: white;border-radius: 10px;box-shadow: rgba(99, 99, 99, 0.2) 0px 2px 8px 0px;">
        <div class="card-body text-center">
          <h1>15</h1>
          <div>
            Est min
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Restaurant Details -->
  <h6 class="mt-3 text-center"><strong>Details</strong></h6>
  <p class="p-show text-center"><%= @restaurant.details %></p>

  <h6 class="mt-3 text-center"><strong>Address</strong></h6>
  <p class="p-show text-center"><%= @restaurant.address %></p>

  <h6 class="mt-3 text-center"><strong>Reviews</strong></h6>


  <!-- Review Card Final -->

   <% @reviews.each do |review| %>
    <div class="review-card-final">
      <div class="review-card">
        <div class="user-info">
            <div class="user-avatar">
              <img src="https://source.unsplash.com/random/?profile&<%= rand(1000) %>" style="background-size: cover; height: 55px;" alt="User Avatar">
            </div>
          <div class="user-name"><%= review.user.name %></div>
        </div>

        <div class="rating">
        <span>Rating: <%= review.rating %></span>
        </div>

        <div class="comment_review_card">
          <h2><%= review.comment %></h2>
        </div>

        <div class="comment_review_card">
          <p><%= review.created_at.strftime("%B %d, %Y") %></p>
        </div>

      </div>
     </div>
  <% end %>
</div>


<!-- Back button -->
<div class="button-container">
  <a href="javascript:history.back()" class="back-to-top">
    <div class="button rounded-left">
      <i class="fas fa-arrow-left"></i>
    </div>
  </a>
  <!-- Second button -->
  <%if !@booking_status || @booking_status.completed == true%>
    <%=link_to "Join Queue", restaurant_join_queue_path(@restaurant.id), class:"button rounded-right", data:{turbo_method: :post}%>

  <%elsif !@booking_status.join%>
    <%=link_to "Leave Queue", booking_path(@booking_status.id), class:"button rounded-right", data:{turbo_method: :delete, confirm: "Are you sure?"}%>
  <%else%>
    <%=link_to "Join Queue", restaurant_join_queue_path(@restaurant.id), class:"button rounded-right", data:{turbo_method: :post}%>
  <%end%>

</div>