q-hopper-backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "review",to: "pages#review"

  # Defines the root path route ("/")
  # root "posts#index"
  get '/map', to: 'restaurants#restaurant_map', as: :restaurant_map
  get '/test', to: 'restaurants#test'


  resources :restaurants do

    resources :reviews, only:[:index, :new, :create, :show]
    post '/join_queue',  to: 'bookings#join_queue'
    patch '/accept_booking', to: 'bookings#accept_booking'
    resources :bookings, only: [:new, :create, :edit, :update,]

    collection do
      get '/italian', to: 'restaurants#italian'
      get '/mexican', to: 'restaurants#mexican'
      get '/indian', to: 'restaurants#indian'
      get '/chinese', to: 'restaurants#chinese'
      get '/thai', to: 'restaurants#thai'
      get '/american', to: 'restaurants#american'
    end
  end
  # Booking routes
  resources :bookings do
    patch :complete_booking, on: :collection

    get :completed, on: :collection
  end
  # Restaurant user view
  resources :venues do
    post '/add_group', to: 'venues#add_group'
  end
end

q-hopper-backend/app/views/pages/home.html.erb
<div class="container-image">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715634537/muomjjojrf9c16bgeoiz.png" style="width: 100%; height: auto; object-fit: cover;">
</div>

<div class="container-home">
  <h1 class="h2 text-center">Bid farewell to those dreaded queues outside your favorite restaurants!</h1>
  <h2 class="h4 text-center">Tired of wasting precious time standing in line? Say goodbye to that inconvenience and hello to seamless dining experiences.</h2>
</div>

<div class="container-home">
    <div class="image-home-two">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1716539109/xl067pe8kdnffl0kba4t.png" style="width: 100%; height: auto; object-fit: cover;">
    </div>

  <div class="text-sections">
    <div class="text-section">
      <h2 class="h3">With Q-Hopper, have fun hopping through queues effortlessly.</h2>
      <p>Simply join virtual queues for multiple restaurants simultaneously, all from the convenience of your phone. Track your position in each queue in real-time and receive notifications when it's your turn to accept a booking.</p>
    </div>

    <div class="text-section">
      <h2 class="h3">Don't run around town being desperate, let them come to you.</h2>
      <p>Once you receive a booking offer, you have 15 minutes to confirm and make your way to the restaurant. No more frantic rushing or missed opportunities – just smooth transitions from queue to table.</p>
    </div>

    <div class="text-section">
      <h2 class="h3">Be spontaneous & adventurous, have many queues on the go! </h2>
      <p>Picture this: multiple queues at your fingertips, each representing a delectable dining destination waiting to be explored. Sign up for Q-Hopper today and start hopping your way to hassle-free dining!</p>
    </div>
  </div>
</div>

<div class="container-home">
  <h1 class="h2 text-center">How it works</h1>
  <h2 class="h4 text-center">Three simple steps to a queue-free dining experience</h2>
  <div class="text-sections">
    <div class="text-section">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715637147/sy1wa8wuqllrtqpjs4g3.png" style="width: 100%; height: auto; object-fit: cover;">
      <h2 class="h3 text-center">Join a Queue</h2>
      <p class="text-center">Find a restaurant you love and join a queue. Browse through a variety of dining options and select the ones that appeal to you. With a simple tap, you can join a virtual queue and monitor your wait time in real-time. Say goodbye to the uncertainty of long waits and hello to better time management!</p>
    </div>

    <div class="text-section">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715637213/u4tifbl5goarfiobbfig.png" style="width: 100%; height: auto; object-fit: cover;">
      <h2 class="h3 text-center">Hangout</h2>
      <p class="text-center">Hang out and wait until you get a notification from the restaurant. Use this time to relax, explore nearby attractions, or simply enjoy your company. You will receive a notification when it's your turn, allowing you to plan your arrival without any stress. Make the most of your time while Q-Hopper manages the queue for you.</p>
    </div>

    <div class="text-section">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1715637245/twruavswnf4apntcw53m.png" style="width: 100%; height: auto; object-fit: cover;">
      <h2 class="h3 text-center">Go to Restaurant</h2>
      <p class="text-center">Get to the venue within the 15 min. Once you receive the notification, head to the restaurant within the specified time frame. Enjoy a seamless transition from queue to table without the hassle of waiting around. Experience the convenience of Q-Hopper and make dining out a truly enjoyable experience.</p>
    </div>
  </div>
</div>


<div class="container-home">
  <h1 class="h2 text-center">Get Started</h1>
  <h2 class="h4 text-center">Sign up to the app and get started today</h2>
  <div class="text-sections">
    <div class="text-section">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1716539836/mf7hcsknxf8d2cdqjrxv.png" style="width: 100%; height: auto; object-fit: cover;">
      <h2 class="h3 text-center">As a Q-Hopper</h2>
      <p class="text-center">Go on, start joining queues from the comfort of your sofa, a bar stall, in a taxi, or riding a hourse. Join anywhere, anytime.</p>

      <div class="button-container-home">
        <a href="<%=  restaurant_map_path %>" class="btn btn-outline-primary mx-2" style="height: 30px; width: 50%; align-content: center;">As Q-Hopper</a>
      </div>

    </div>

    <div class="text-section">
      <img src="https://res.cloudinary.com/dqbiijjlp/image/upload/v1716539835/rkvcx0nkfkuxas9hzcdm.png" style="width: 100%; height: auto; object-fit: cover;">
      <h2 class="h3 text-center">As a Restaurant</h2>
      <p class="text-center">Fed up of people canceling reservations last minuite. No worries. Maintain a constant virtual que with ready customers. </p>

      <div class="button-container-home">
       <a href="<%= venues_path %>" class="btn btn-outline-primary mx-2" style="height: 30px; width: 50%; align-content: center;">As Restaurant</a>
      </div>

    </div>

  </div>
</div>


<footer class="footer-home">
    <p>© 2024 Q-HOPPER. All rights reserved.</p>
    <p>Designed and developed by Le Wagon students.</p>
</footer>