q-hopper-backend/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  get "review",to: "pages#review"

  # Defines the root path route ("/")
  # root "posts#index"
  get '/map', to: 'restaurants#restaurant_map', as: :restaurant_map
  get '/test', to: 'restaurants#test'


  resources :restaurants do

    resources :reviews, only:[:index, :new, :create, :show]
    post '/join_queue',  to: 'bookings#join_queue'
    patch '/accept_booking', to: 'bookings#accept_booking'
    resources :bookings, only: [:new, :create, :edit, :update,]

    collection do
      get '/italian', to: 'restaurants#italian'
      get '/mexican', to: 'restaurants#mexican'
      get '/indian', to: 'restaurants#indian'
      get '/chinese', to: 'restaurants#chinese'
      get '/thai', to: 'restaurants#thai'
      get '/american', to: 'restaurants#american'
    end
  end
  # Booking routes
  resources :bookings do
    patch :complete_booking, on: :collection

    get :completed, on: :collection
  end
  # Restaurant user view
  resources :venues do
    post '/add_group', to: 'venues#add_group'
  end
end

q-hopper-backend/app/controllers/venues_controller.rb
class VenuesController < ApplicationController
  before_action :set_venue, only: [:show]
  def index
    @venues = Restaurant.where(user: current_user)
    @bookings = Booking.includes(:restaurant).where(restaurant: {user: current_user})
  end

  def show
    @bookings = Booking.where(restaurant: @venue)
  end

  def add_group

    @front_of_queue = Booking.find_by(restaurant_id:params[:venue_id], join: false)
    @bookings = Booking.where(restaurant_id: params[:venue_id])
    user = User.find(2)
    @front_of_queue.update(join: true)
    @front_of_queue.save
    RestaurantChannel.broadcast_to(
      user,
      render_to_string(partial:'shared/accept_booking',locals:{restaurant_id: params[:venue_id], booking_id: @front_of_queue.id})
    )
    redirect_to venue_path(params[:venue_id])

  end

  private

  def set_venue
    @venue = Restaurant.find(params[:id])

  end
end

q-hopper-backend/app/views/venues/_queue.html.erb
<div class="container">
  <h2 class= 'mt-2 text-center'><%=title%></h2>
  <%= render 'queue_info', value: groups.size, parameter: parameter%>
  <div class="venue-queue-list pt-1 mt-2 bg-route">
    <%if groups.empty?%>
      <p class =d-flex align-items-center>Queue is empty</p>
    <%else%>
      <%groups.each do |group|%>
      <%if group.completed
          card_type = :normal
        elsif group.accepted
          card_type = :accepted
        elsif group.join
          card_type = :warning
        else
          card_type = :normal
        end

      %>
        <%= render 'queue_card', name: group.user.name, group_size: rand(1...4), card_type: card_type, updated_at: group.updated_at, booking_id: group.id%>
      <%end%>
    <%end%>
  </div>
</div>

q-hopper-backend/app/views/venues/_queue_card.html.erb
<div data-controller='accept-booking' data-accept-booking-booking-id-value= "<%=booking_id%>">
  <%card_types = {accepted: 'booking-success', warning: 'booking-warning', normal: "" }%>

  <div class="card mt-1 <%=card_types[card_type]%> rounded-4" data-action = "<%=card_type == :accepted ? 'click->acceptBooking#arrived': ''%>">
    <div class="card-body" data-action = "click->accept-booking#arrived">
      <div class="d-flex justify-content-between">
        <h5 class= "card-title text-start"><%= name %></h5>
        <div class="queue-position p-1">
          <p><%= group_size%></p>
          seats
        </div>
      </div>
    </div>
  </div>
  <%if card_type == :accepted || card_type == :warning%>
    <%= render 'time_left', updated_at: updated_at, booking_id: booking_id, card_type: card_type%>
  <%end%>

</div>

q-hopper-backend/app/views/venues/_queue_controls.erb
<div class="venue-queue-button d-flex justify-content-center p-3">
  <%if empty_queue%>

      <div class="add-booking">
        <%= button_to "Accept next group", venue_add_group_path(venue),class: 'btn btn-info disabled rounded'%>
    </div>
  <%else%>
    <div class="add-booking">
      <%= button_to "Accept next group", venue_add_group_path(venue), class: 'btn btn-primary'%>
    </div>
  <%end%>
</div>

<div class= container>
  <form action="post" class="d-flex">
    <div class="mb-3">
      <label for="booking-code" class = "form-label">Enter Booking code</label>
      <input type='text' class="form-controll" id ="booking-code">
    </div>
    <button type ='submit' class= 'btn btn-primary'></button>
  </form>
</div>

q-hopper-backend/app/views/venues/_queue_info.html.erb
<div>
  <div class="container bg-primary rounded-5 text-white p-1 text-center">
    <h2> <%=value%>  </h2>
    <p class="p-0 m-0"><%=parameter%></p>

  </div>

</div>

q-hopper-backend/app/views/venues/_restaurant_card.html.erb
<div class="card-booking" style="background-image: linear-gradient(rgba(18, 16, 16, 0.9), rgba(62, 53, 53, 0.5)), url('https://source.unsplash.com/random/?restaurant&<%= rand(1000) %>'); background-size: cover; background-position: center;">
    <div class="card-header">
        <h2><%= restaurant.name%></h2>
    </div>
    <div class="card-body">
      <p> Queue size: <strong><%=booking_amount%> </strong> </p>
    </div>
    <div class="card-footer">

          <%=link_to "Go to restaurant", venue_path(restaurant.id), class: "btn btn-primary text-white text-medium"%>

    </div>
</div>

q-hopper-backend/app/views/venues/_time_left.html.erb
    <div class="venue-booking-information bg-primary p-1 rounded-4 rounded-top-0 text-center"
    data-controller ='countdown'
    data-countdown-target = 'timer'
    data-countdown-text-value = "<%=updated_at%>"
    data-countdown-booking-value = "<%=booking_id%>"
    data-countdown-card-type-value = "<%= card_type.to_s%>">

    </div>

q-hopper-backend/app/views/venues/index.html.erb
<h1 class='text-center'> <strong>Your Venues</strong></h1>
<div class="venue-container-grid">
  <div class="row">
    <%@venues.each do |venue|%>
      <div class="col">
      <%= render 'restaurant_card', restaurant: venue, booking_amount: Booking.where(restaurant: venue, join: false).count%>
      </div>
    <%end%>

  </div>

</div>

<div class="d-flex justify-content-center">
  <%= link_to "Log out!", destroy_user_session_path, class: 'btn btn-lg btn-primary text-white', data: {turbo_method:'delete', confirm: "Are you sure?"}%>
</div>

q-hopper-backend/app/views/venues/show.html.erb
<h1 class="text-center"> <strong> <%=@venue.name%> </strong>   </h1>
<div class="venue-queue-container bg-light rounded-5 border" >
  <div class="row w-60">
      <div class="col ">
        <%= render 'queue', groups: @bookings.where(accepted:false), title: "Queue", parameter:"Queue Size"%>


        <div class="d-flex justify-content-center p-3">

        </div>



        </div>

        <div class="col">
          <%= render 'queue', groups: @bookings.where(completed:false, accepted:true), title: "Accepted", parameter: "On Route"%>
        </div>
        <div class="col">
          <%=render 'queue', groups: @bookings.where(completed:true, accepted:true), title: 'Completed', parameter: 'Completed Bookings'%>
        </div>
  </div>

</div>
<div class="d-flex justify-content-center mt-4">

  <div class="add-booking d-flex justify-content-centre">
    <%if @bookings.where(accepted:false, completed:false, join:false).empty?%>
      <div class="add-booking">
          <%= button_to "Accept next group", venue_add_group_path(@venue),class: 'btn btn-lg btn-info disabled rounded-5'%>
      </div>
    <%else%>
      <%= button_to "Accept next group", venue_add_group_path(@venue), class: 'btn btn-lg btn-primary rounded-5 text-white'%>
    <%end%>
  </div>
</div>